apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kubeHooks
  name: kubeHooks
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kubeHooks
    spec:
      containers:
      - image: soren365/kubehooks:1.0
        name: kubeHooks
        ports:
        - containerPort: 5000
            resources:
      {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
status: {}
