apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helmcharts/avantweb/templates
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: avant-mailserver
  name: avant-mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: avant-mailserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helmcharts/avantweb/templates
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: avant-mailserver
    spec:
      containers:
      - image: soren365/avant-mail:1.02
        imagePullPolicy: ""
        name: avant-mailserver
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
