apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helmcharts/avantweb/templates
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: avant-proxyserver
  name: avant-proxyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: avant-proxyserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helmcharts/avantweb/templates
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: avant-proxyserver
    spec:
      containers:
      - image: soren365/avant-proxy:1.0
        imagePullPolicy: ""
        name: avant-proxyserver
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
