apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helmcharts/avantweb/templates
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: avant-website
  name: avant-website
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: avant-website
status:
  loadBalancer: {}
